# Define the goal
string[] controlled_joints  #All the joints to use for this action
string controller_yaml      #The complete content of the generated controller yaml
string feedbackValue
suturo_manipulation_msgs/TypedParam[] params
#Params for the action like:
#"frame: cylinder"
#"width: 0.06"
#"height: 0.2"
---
# Define the result
uint8 PREEMPTED=0
uint8 INFEASIBLE_GOAL=1
uint8 TERMINATED=2
uint8 INVALID_DATATYPE=3
uint8 DEFECT_YAML=4
uint8 DEFECT_CONTROLLER=5
uint8 INVALID_FEEDBACK=6
uint8 reason_for_termination
---
# Define a feedback message
float64 current_value
float64 alteration_rate
# Define the goal
#string[] controlled_joints             #All the joints to use for this action
#string controller_yaml                 #The complete content of the generated controller yaml
#Params for the action like:
#"frame: cylinder"
#"width: 0.06"
#"height: 0.2"
#diagnostic_msgs/KeyValue[] params
#---
# Define the result
#uint32 reason_for_termination
#---
# Define a feedback message
#float64 current_value
#float64 alteration_rate